env:
  global:
    - CC_TEST_REPORTER_ID=57d409ab83be84f6964ef5298e3dc9e77b01a254e302dcec597002ee6209d07e
language: node_js
node_js:
- 9.4.0
- 8.9.4
- 7.10.1
- 6.12.3
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
